#############################################################################
# Makefile for building: FormTest
# Generated by qmake (2.01a) (Qt 4.6.3) on: ven. mai 11 20:37:09 2012
# Project:  FormTest.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile FormTest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sliderhandle.cpp \
		doublesliderwidget.cpp \
		filterform.cpp \
		genrecheckbox.cpp \
		filmdummy.cpp \
		filmdisplay.cpp moc_doublesliderwidget.cpp \
		moc_filterform.cpp \
		moc_genrecheckbox.cpp \
		moc_filmdisplay.cpp
OBJECTS       = main.o \
		sliderhandle.o \
		doublesliderwidget.o \
		filterform.o \
		genrecheckbox.o \
		filmdummy.o \
		filmdisplay.o \
		moc_doublesliderwidget.o \
		moc_filterform.o \
		moc_genrecheckbox.o \
		moc_filmdisplay.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FormTest.pro
QMAKE_TARGET  = FormTest
DESTDIR       = 
TARGET        = FormTest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_filterform.h ui_filmdisplay.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FormTest.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile FormTest.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile FormTest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FormTest1.0.0 || $(MKDIR) .tmp/FormTest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FormTest1.0.0/ && $(COPY_FILE) --parents sliderhandle.h doublesliderwidget.h filterform.h genrecheckbox.h filmdummy.h filmdisplay.h .tmp/FormTest1.0.0/ && $(COPY_FILE) --parents main.cpp sliderhandle.cpp doublesliderwidget.cpp filterform.cpp genrecheckbox.cpp filmdummy.cpp filmdisplay.cpp .tmp/FormTest1.0.0/ && $(COPY_FILE) --parents filterform.ui filmdisplay.ui .tmp/FormTest1.0.0/ && (cd `dirname .tmp/FormTest1.0.0` && $(TAR) FormTest1.0.0.tar FormTest1.0.0 && $(COMPRESS) FormTest1.0.0.tar) && $(MOVE) `dirname .tmp/FormTest1.0.0`/FormTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FormTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_doublesliderwidget.cpp moc_filterform.cpp moc_genrecheckbox.cpp moc_filmdisplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_doublesliderwidget.cpp moc_filterform.cpp moc_genrecheckbox.cpp moc_filmdisplay.cpp
moc_doublesliderwidget.cpp: sliderhandle.h \
		doublesliderwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) doublesliderwidget.h -o moc_doublesliderwidget.cpp

moc_filterform.cpp: doublesliderwidget.h \
		sliderhandle.h \
		genrecheckbox.h \
		filterform.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filterform.h -o moc_filterform.cpp

moc_genrecheckbox.cpp: genrecheckbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) genrecheckbox.h -o moc_genrecheckbox.cpp

moc_filmdisplay.cpp: filmdisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filmdisplay.h -o moc_filmdisplay.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_filterform.h ui_filmdisplay.h
compiler_uic_clean:
	-$(DEL_FILE) ui_filterform.h ui_filmdisplay.h
ui_filterform.h: filterform.ui
	/usr/bin/uic-qt4 filterform.ui -o ui_filterform.h

ui_filmdisplay.h: filmdisplay.ui
	/usr/bin/uic-qt4 filmdisplay.ui -o ui_filmdisplay.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp filterform.h \
		doublesliderwidget.h \
		sliderhandle.h \
		genrecheckbox.h \
		filmdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sliderhandle.o: sliderhandle.cpp sliderhandle.h \
		doublesliderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sliderhandle.o sliderhandle.cpp

doublesliderwidget.o: doublesliderwidget.cpp doublesliderwidget.h \
		sliderhandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublesliderwidget.o doublesliderwidget.cpp

filterform.o: filterform.cpp filterform.h \
		doublesliderwidget.h \
		sliderhandle.h \
		genrecheckbox.h \
		ui_filterform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterform.o filterform.cpp

genrecheckbox.o: genrecheckbox.cpp genrecheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genrecheckbox.o genrecheckbox.cpp

filmdummy.o: filmdummy.cpp filmdummy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filmdummy.o filmdummy.cpp

filmdisplay.o: filmdisplay.cpp filmdisplay.h \
		ui_filmdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filmdisplay.o filmdisplay.cpp

moc_doublesliderwidget.o: moc_doublesliderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_doublesliderwidget.o moc_doublesliderwidget.cpp

moc_filterform.o: moc_filterform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filterform.o moc_filterform.cpp

moc_genrecheckbox.o: moc_genrecheckbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_genrecheckbox.o moc_genrecheckbox.cpp

moc_filmdisplay.o: moc_filmdisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filmdisplay.o moc_filmdisplay.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

